### ISSUE TITLE
No such file or directory: '/usr/lib/x86_64-linux-gnu/openblas-pthread/'

### ISSUE THREAD

**Issue by dia96** [KBicz/BASSMAN#2]
I am running bassman.py on my laptop, I seem to be having issue which attached below.

(bassman) diya@diya-laptop:~/BASSMAN-main$ python3 bassman.py -star=star_params.npz 

> Estimating model no. 1 for 1 spots.
Traceback (most recent call last):
  File "bassman.py", line 1314, in <module>
    recreate_sspots(params,nspots,prec,dprec,prs,omb,obm,def_inclination,gv,ylm,stara,alpha,alu,slu,lalu,lolu,adap,mprod,savectrl,save,force,displayctrl,sample,noadap,finc,gsp,nstep,diffctrl,filterctrl,fulltime,nosphere,command,modelfile,modelctrl,staractrl,tbjd,tbjdctrl,initctrl,ncores,nchains,chiv,logpv,chivctrl,logpvctrl,nochi,temper,temperctrl,check,pcom,ps,fscale,pran,falpha,falphactrl,publication,liveplot,terrctrl,terr,modelonly,nth)
  File "bassman.py", line 538, in recreate_sspots
    flux_model_guess = pmx.eval_in_model(flux_model).copy()
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/exoplanet/utils.py", line 97, in eval_in_model
    func = get_theano_function_for_var(var, model=model, **kwargs)
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/exoplanet/utils.py", line 71, in get_theano_function_for_var
    return theano.function(model.vars, var, **kwargs)
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/compile/function/__init__.py", line 337, in function
    fn = pfunc(
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/compile/function/pfunc.py", line 538, in pfunc
    return orig_function(
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/compile/function/types.py", line 1997, in orig_function
    fn = m.create(defaults)
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/compile/function/types.py", line 1850, in create
    _fn, _i, _o = self.linker.make_thunk(
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/link.py", line 738, in make_thunk
    return self.make_all(
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/vm.py", line 1145, in make_all
    node.op.make_thunk(node, storage_map, compute_map, [], impl=impl)
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/op.py", line 981, in make_thunk
    return self.make_c_thunk(node, storage_map, compute_map, no_recycling)
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/op.py", line 878, in make_c_thunk
    outputs = cl.make_thunk(
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/cc.py", line 1274, in make_thunk
    cthunk, module, in_storage, out_storage, error_storage = self.__compile__(
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/cc.py", line 1203, in __compile__
    thunk, module = self.cthunk_factory(
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/cc.py", line 1696, in cthunk_factory
    key = self.cmodule_key()
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/cc.py", line 1355, in cmodule_key
    return self.cmodule_key_(
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/cc.py", line 1531, in cmodule_key_
    version.append(node.op.c_code_cache_version_apply(node))
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/op.py", line 387, in c_code_cache_version_apply
    return self.c_code_cache_version()
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/tensor/blas_c.py", line 639, in c_code_cache_version
    return (14, blas_header_version(), check_force_gemv_init())
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/tensor/blas_c.py", line 688, in check_force_gemv_init
    flags=ldflags(libs=True, flags=True, libs_dir=True),
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/tensor/blas.py", line 410, in ldflags
    return _ldflags(
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/gof/utils.py", line 298, in rval
    val = f(*args, **kwargs)
  File "/home/diya/anaconda3/envs/bassman/lib/python3.8/site-packages/theano/tensor/blas.py", line 457, in _ldflags
    for f in os.listdir(d.strip('"')):
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/x86_64-linux-gnu/openblas-pthread/'
(bassman) diya@diya-laptop:~/BASSMAN-main$

**Comment by rajph0** [comment]
Run this below command, it will resolve this issue.
"sudo apt-get install libopenblas-pthread-dev"

**Comment by dia96** [comment]
Thank you for solving this issue.
